openapi: 3.0.1
info:
  title: User Registration
  description: User CRUD API
  version: 1.0.0
servers:
  - url: /v1
paths:
  /user/{userId}:
    get:
      tags:
        - user
      summary: Get User
      operationId: getUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/User'

  /user:
    get:
      summary: Get Users
      operationId: getUsers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Add a User
      operationId: addUser
      requestBody:
        description: User to be added in.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: User Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: user
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: Kelly
        lastName:
          type: string
          example: Sanderson
        age:
          type: integer
          format: 45
          example: 24